[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["WildcatMarket"]
fs_permissions = [{ access = "read-write", path = "./deployments.json"}]

# via_ir = true
optimizer = true
optimizer_runs = 1

remappings = [
  'forge-std/=lib/forge-std/src/',
  'ds-test/=lib/ds-test/src/',
  'solmate/=lib/solmate/src/',
  'solady/=lib/solady/src/',
  'sol-utils/=lib/sol-utils/src/',
  'openzeppelin/=lib/openzeppelin-contracts/',
  "@spherex-xyz/contracts/src/=lib/spherex-protect-contracts/src/",
]

evm_version = 'shanghai'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.fuzz]
runs = 1000

[invariant]
runs = 2000
depth = 30
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true


# // Original SphereX code, 200 optimizer runs
# IR: WildcatMarket | init: 34331 | runtime: 29500
# Not IR: WildcatMarket | init: 28324 | runtime: 24009

# // Original SphereX code, 1 optimizer run
# IR: WildcatMarket | init: 33381 (-950) | runtime: 28645 (-855)
# Not IR: WildcatMarket | init: 27904 (-420)  | runtime: 23581 (-428)

# // Minimal SphereX code, 1 optimizer runs
# IR: WildcatMarket | init: 25135 (-8246) | runtime: 20533 (-8112)
# Not IR: WildcatMarket | init: 26346 (-1558)  | runtime: 22104 (-1477)