[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["WildcatMarket"]
fs_permissions = [{ access = "read-write", path = "./deployments.json"}]

# via_ir = true

remappings = [
  'forge-std/=lib/forge-std/src/',
  'ds-test/=lib/ds-test/src/',
  'solmate/=lib/solmate/src/',
  'solady/=lib/solady/src/',
  'sol-utils/=lib/sol-utils/src/',
  'openzeppelin/=lib/openzeppelin-contracts/',
]

evm_version = 'shanghai'

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default.fuzz]
runs = 1000

[invariant]
runs = 2000
depth = 30
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true